# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Ivan Gavrilovic
tagline:          Internet Addict, Geek, The Startup Guy
url:              http://gavra0.github.io/igavrilovic/
paginate:         1
baseurl:          /igavrilovic
author:
  name:           Ivan Gavrilovic
  url:            https://twitter.com/gavra0
  email:          gavra0@gmail.com

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
